### ISSUE TITLE
ZDE resolves root domain when only *.contoso.net sub-domains should

### ISSUE THREAD

**Issue by nenkoru** [openziti/ziti-tunnel-apple#198]
So I've been exploring the possibility of joining an Active Directory domain with another Windows machine, which btw went fine with ZDEW 2.5.0.11. 
I have encountered an issue where a ZDE for MacOS[2] would resolve contoso.net(as per example config)[1], when `addresses` is only set to `"*.contoso.net"`. It resolves the root domain(contoso.net) and tries to route the request to the overlay and eventually gets refused[3]. This is resolved by adding a root "contoso.net" into the `allowedAdresses`[4] of the host config, but I expected that the DNS server would not even resolve the root domain. Or if resolved, I expect it to be routed and a connection established.

[1] https://gist.github.com/nenkoru/303c8ad08d02a74947ad73b54b783ff9
[2] Version 2.47 (525)(appstore)
[3]
```bash
➜  ~ telnet contoso.net 389
Trying 100.64.0.23...
telnet: connect to address 100.64.0.23: Connection refused
telnet: Unable to connect to remote host
```
[4]
```bash
➜  ~ telnet contoso.net 389
Trying 100.64.0.23...
Connected to contoso.net.
Escape character is '^]'.
``` 

upd: edited the title and slightly changed the issue

**Comment by scareything** [comment]
Hi and thanks for the issue.

Unfortunately I'm not sure that we can do anything about this, since the macOS resolver does not provide a way to specify a "wildcard" domain as we support with ziti-edge-tunnel. On macOS, the resolver effectively treats _all_ domains as wildcards. A relevant excerpt from the [resolver(5)](https://www.unix.com/man-page/osx/5/resolver/) man page:

> The matching algorithm chooses the client with the maximum number of matching domain components.

So when the apple tunnelers process an intercept configuration with a wildcard domain such as "*.centoso.net", they configure the host's resolver with the domain minus the leading "*.". You can see this for yourself with `scutil --dns`.

Maybe there's a trick to it that I'm not aware of, but as far as I know there's no way to specify that the root domain should not be matched on macOS.

**Comment by nenkoru** [comment]
> Hi and thanks for the issue.
> 
> Unfortunately I'm not sure that we can do anything about this, since the macOS resolver does not provide a way to specify a "wildcard" domain as we support with ziti-edge-tunnel. On macOS, the resolver effectively treats _all_ domains as wildcards. A relevant excerpt from the [resolver(5)](https://www.unix.com/man-page/osx/5/resolver/) man page:
> 
> > The matching algorithm chooses the client with the maximum number of matching domain components.
> 
> So when the apple tunnelers process an intercept configuration with a wildcard domain such as "_.centoso.net", they configure the host's resolver with the domain minus the leading "_.". You can see this for yourself with `scutil --dns`.
> 
> Maybe there's a trick to it that I'm not aware of, but as far as I know there's no way to specify that the root domain should not be matched on macOS.

I see.
I didn't have time to test this behaviour in general with Linux installations. Do you think this could be happening in Linux too?
Also maybe it would be a good idea to mention this behaviour in a doc where allowedAddress is mentioned?

**Comment by nenkoru** [comment]
Upd: idk, but I can't reproduce the original issue. The connection is not getting refused.

**Comment by nenkoru** [comment]
Alright, can't reproduce the original issue anymore, will reopen if would find a reproducible setup.
